# Generated by Django 4.1.4 on 2023-01-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encyclopedia", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Entry",
        ),
    ]
